name: Deploy GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Remove heavy folders and Blu before artifact upload
        run: |
          rm -rf big_json
          rm -rf cache
          rm -rf output_audio
          rm -rf thumbnails

          # EXCLUDE Blu from the artifact (but keep it in the repo)
          rm -rf Blu

          # EXCLUDE your new huge JSON from the artifact
          rm -f axd_index_datefixed_rawurls.json

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
